# Generated by Django 5.2.12 on 2026-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramo'), ('ml', 'Mililitro'), ('un', 'Unidad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ingredientmovement',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ingredientmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE_CONSUMPTION', 'Consumo por venta'), ('MANUAL_ADJUSTMENT', 'Ajuste manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('REAL_TIME', 'Tiempo real'), ('DAILY_CLOSE', 'Cierre diario')], max_length=20),
        ),
    ]
