# Generated by Django 5.2.12 on 2026-03-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_total_cost_sale_total_profit_sale_total_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='source',
        ),
    ]
