from django.urls import path

from core.views import (
    CustomerCreateView,
    CustomerDeleteView,
    CustomerListView,
    CustomerUpdateView,
    DashboardView,
    IngredientAdjustStockView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientListView,
    IngredientUpdateView,
    OrderCreateView,
    OrderDeleteView,
    OrderListView,
    OrderUpdateView,
    PizzaCreateView,
    PizzaDeleteView,
    PizzaListView,
    PizzaUpdateView,
    RecipeItemCreateView,
    RecipeItemDeleteView,
    RecipeItemListView,
    RecipeItemUpdateView,
    SaleCloseDayView,
    SaleListView,
)

app_name = "core"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("sales/", SaleListView.as_view(), name="sale_list"),
    path("sales/close-day/", SaleCloseDayView.as_view(), name="sale_close_day"),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/new/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/edit/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("customers/", CustomerListView.as_view(), name="customer_list"),
    path("customers/new/", CustomerCreateView.as_view(), name="customer_create"),
    path("customers/<int:pk>/edit/", CustomerUpdateView.as_view(), name="customer_update"),
    path("customers/<int:pk>/delete/", CustomerDeleteView.as_view(), name="customer_delete"),
    path("ingredients/", IngredientListView.as_view(), name="ingredient_list"),
    path("ingredients/new/", IngredientCreateView.as_view(), name="ingredient_create"),
    path("ingredients/<int:pk>/edit/", IngredientUpdateView.as_view(), name="ingredient_update"),
    path("ingredients/<int:pk>/adjust-stock/", IngredientAdjustStockView.as_view(), name="ingredient_adjust_stock"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient_delete"),
    path("pizzas/", PizzaListView.as_view(), name="pizza_list"),
    path("pizzas/new/", PizzaCreateView.as_view(), name="pizza_create"),
    path("pizzas/<int:pk>/edit/", PizzaUpdateView.as_view(), name="pizza_update"),
    path("pizzas/<int:pk>/delete/", PizzaDeleteView.as_view(), name="pizza_delete"),
    path("recipes/", RecipeItemListView.as_view(), name="recipe_list"),
    path("recipes/new/", RecipeItemCreateView.as_view(), name="recipe_create"),
    path("recipes/<int:pk>/edit/", RecipeItemUpdateView.as_view(), name="recipe_update"),
    path("recipes/<int:pk>/delete/", RecipeItemDeleteView.as_view(), name="recipe_delete"),
]
